feat: add option to skip resolving transitive local package dependencies (#1493)
Time spent transitively resolving dependencies on local Swift packages
grows linearly with the number of local packages used. On my M1 Max
MacBook Pro time spent resolving transitive local package dependencies
is ~1.5s per local package. This work happens sequentially and it must
complete before any of the individual package repositories, either local
or remote, can be created/fetched.

The image below shows the `swift_deps` extension taking a little over
one minute to run using the current approach.

<img width="783" alt="Screenshot 2025-02-16 at 2 51 57 PM"
src="https://github.com/user-attachments/assets/643a02fb-dd21-4f24-b218-7ba085476d46"
/>

This PR adds a configuration option to skip resolving transitive local
dependencies which can provide considerable time savings in exchange for
requiring every local Swift package needed for the build to be directly
defined in the `Package.swift` file.

The image below shows the `swift_deps` extension taking just over one
second to run by skipping transitive local package resolution using the
proposed configuration flag.

<img width="735" alt="Screenshot 2025-02-16 at 2 51 41 PM"
src="https://github.com/user-attachments/assets/4ccdc909-4352-4c71-b435-db1e114acd02"
/>

If developers fail declare all of the local Swift packages required to
perform a build in their `Package.swift` file they will see an error
similar to this:
```
ERROR: no such package '@@[unknown repo 'swiftpkg_dashchatsdk' requested from @@rules_swift_package_manager~~swift_deps~swiftpkg_ddchat]//': The repository '@@[unknown repo 'swiftpkg_dashchatsdk' requested from @@rules_swift_package_manager~~swift_deps~swiftpkg_ddchat]' could not be resolved: No repository visible as '@swiftpkg_dashchatsdk' from repository '@@rules_swift_package_manager~~swift_deps~swiftpkg_ddchat'
ERROR: /private/var/tmp/_bazel_johnflanagan/05ccc23d6031bc6f89e0b3a69d0edab6/external/rules_swift_package_manager~~swift_deps~swiftpkg_ddchat/BUILD.bazel:79:14: no such package '@@[unknown repo 'swiftpkg_dashchatsdk' requested from @@rules_swift_package_manager~~swift_deps~swiftpkg_ddchat]//': The repository '@@[unknown repo 'swiftpkg_dashchatsdk' requested from @@rules_swift_package_manager~~swift_deps~swiftpkg_ddchat]' could not be resolved: No repository visible as '@swiftpkg_dashchatsdk' from repository '@@rules_swift_package_manager~~swift_deps~swiftpkg_ddchat' and referenced by '@@rules_swift_package_manager~~swift_deps~swiftpkg_ddchat//:DDChat.rspm'
ERROR: Analysis of target '//:DoorDash' failed; build aborted: Analysis failed
```
where `dashchatsdk` is the local package that is depended on by
`ddchat`, but wasn't declared in the `Package.swift` file.

---------

Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>