fix: improve xcframework archive file link type detection (#1102)
- If RSPM cannot infer the link type from `file --brief`, use `otool -l`
to see if the library is `dynamic`, and if not default to `static`.
- Add a subset of the [Google Maps
Demos](https://github.com/googlemaps-samples/maps-sdk-for-ios-samples/tree/main/GoogleMaps-Swift)
to the project.
- The example needed to be patched, as there's an error with `@import
GoogleMaps;` in the headers for the frameworks otherwise.
	FYI, the error is:
    ```

external/rules_swift_package_manager~~swift_deps~swiftpkg_ios_maps_sdk/Core/GMSEmpty.m:17:9:
fatal error: module 'GoogleMaps' not found
	@import GoogleMaps;
	 ~~~~~~~^~~~~~~~~~
	1 error generated.
    ```
I quickly looked into it but couldn't find an easy fix, so patching
seemed like the easiest solution.

cc @cgrindel - would love feedback on this! I didn't do any processing
on the `otool -l` command as I didn't think it to be necessary.

Closes #1084

---------

Co-authored-by: Chuck Grindel <chuck.grindel@gmail.com>