chore(deps): update dependency vapor/vapor to v4.121.4 (#2197)
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [vapor/vapor](https://redirect.github.com/vapor/vapor) | minor |
`4.117.1` → `4.121.4` |

---

### Release Notes

<details>
<summary>vapor/vapor (vapor/vapor)</summary>

###
[`v4.121.4`](https://redirect.github.com/vapor/vapor/releases/tag/4.121.4):
- Fix Response Compression Bug when Content Type header is empty

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.121.3...4.121.4)

#### What's Changed

Fix Response Compression Bug when Content Type header is empty by
[@&#8203;0xTim](https://redirect.github.com/0xTim) in
[#&#8203;3453](https://redirect.github.com/vapor/vapor/issues/3453)

> Fixes a bug in the response compression pipeline where the response
would be compressed, even if response compression is disabled, if no
content-type header was set for the response.

###### *This patch was released by
[@&#8203;0xTim](https://redirect.github.com/0xTim)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.121.3...4.121.4>

###
[`v4.121.3`](https://redirect.github.com/vapor/vapor/releases/tag/4.121.3):
- Parse directives from all Cookie headers, not just the first

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.121.2...4.121.3)

#### What's Changed

Parse directives from all Cookie headers, not just the first by
[@&#8203;gwynne](https://redirect.github.com/gwynne) in
[#&#8203;3436](https://redirect.github.com/vapor/vapor/issues/3436)

> Fixes
[#&#8203;3435](https://redirect.github.com/vapor/vapor/issues/3435).

#### Reviewers

Thanks to the reviewers for their help:

- [@&#8203;ptoffy](https://redirect.github.com/ptoffy)
- [@&#8203;MahdiBM](https://redirect.github.com/MahdiBM)

###### *This patch was released by
[@&#8203;0xTim](https://redirect.github.com/0xTim)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.121.2...4.121.3>

###
[`v4.121.2`](https://redirect.github.com/vapor/vapor/releases/tag/4.121.2):
- Add Sendable conformance to application testing Method type

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.121.1...4.121.2)

#### What's Changed

Add Sendable conformance to application testing Method type by
[@&#8203;tib](https://redirect.github.com/tib) in
[#&#8203;3424](https://redirect.github.com/vapor/vapor/issues/3424)

> This PR adds `Sendable` conformance to the `Method` type in the
`VaporTestUtils` target.

#### New Contributor

- [@&#8203;tib](https://redirect.github.com/tib) made their first
contribution in
[#&#8203;3424](https://redirect.github.com/vapor/vapor/issues/3424) 🎉

###### *This patch was released by
[@&#8203;0xTim](https://redirect.github.com/0xTim)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.121.1...4.121.2>

###
[`v4.121.1`](https://redirect.github.com/vapor/vapor/releases/tag/4.121.1):
- Do not create a session if no cookie was provided

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.121.0...4.121.1)

#### What's Changed

Do not create a session if no cookie was provided by
[@&#8203;czechboy0](https://redirect.github.com/czechboy0) in
[#&#8203;3372](https://redirect.github.com/vapor/vapor/issues/3372)

> ## Summary
>
> When using `SessionsMiddleware` and a custom
`AsyncSessionAuthenticator` together, we were seeing that even in cases
when no cookie is provided in the request, and no error was thrown by
e.g. a guard middleware or the handler, we were still seeing a
`set-cookie` header in the response, which isn’t desired.
>
> This lead to many sessions created in the sessions driver for calls
that didn’t require authentication, nor did it provide any.
>
> This seemed to be a side effect of the way `AsyncSessionAuthenticator`
checked if the session already contained an authenticated value - by
using the getter `request.session`, a session was created lazily.
>
> The fix is to prepend a check to `request.hasSession` and only using
`request.session...` if one indeed exists.
>
> ## Test Plan
>
> A regression test was added which exercises this scenario - and it
fails without the fix.

###### *This patch was released by
[@&#8203;0xTim](https://redirect.github.com/0xTim)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.121.0...4.121.1>

###
[`v4.121.0`](https://redirect.github.com/vapor/vapor/releases/tag/4.121.0):
- The RouteNotFound that is used when the router finds nothing is now
public

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.120.0...4.121.0)

#### What's Changed

The RouteNotFound that is used when the router finds nothing is now
public by [@&#8203;fizker](https://redirect.github.com/fizker) in
[#&#8203;3326](https://redirect.github.com/vapor/vapor/issues/3326)

> When no routes match the current request, `DefaultResponder` throws
the `RouteNotFound` error.
>
> This PR makes that error public, allowing any middleware to handle
that specific scenario.
>
> Unlike the CatchAll route `**`, a middleware catching the
`RouteNotFound` works across all HTTP methods automatically.
>
> This would be used in a middleware like so:
>
> ```swift
> public struct CatchAllMiddleware: AsyncMiddleware {
> public func respond(to request: Request, chainingTo next: any
AsyncResponder) async throws -> Response {
>         do {
>             return try await next.respond(to: request)
>         } catch is RouteNotFound {
> // No route was found, so this would normally result in a 404.
>             // We can now handle this like any other request.
> // Or we can make treat it like an ErrorMiddleware where we
> // log purposeful 404s different than `RouteNotFound` 404s.
>             ...
>         }
>     }
> }
> ```

###### *This patch was released by
[@&#8203;0xTim](https://redirect.github.com/0xTim)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.120.0...4.121.0>

###
[`v4.120.0`](https://redirect.github.com/vapor/vapor/releases/tag/4.120.0):
- Fix compatibility with swift-log 1.8.0 and later

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.119.2...4.120.0)

#### What's Changed

Fix compatibility with swift-log 1.8.0 and later by
[@&#8203;gwynne](https://redirect.github.com/gwynne) in
[#&#8203;3412](https://redirect.github.com/vapor/vapor/issues/3412)

> [swift-log](https://redirect.github.com/apple/swift-log) introduced
`CustomStringConvertible` and `LosslessStringConvertible` conformances
on `Logger.Level` which cause build errors by conflicting with our
implementations, so ours are now gone.

#### Reviewers

Thanks to the reviewers for their help:

- [@&#8203;ptoffy](https://redirect.github.com/ptoffy)

###### *This patch was released by
[@&#8203;gwynne](https://redirect.github.com/gwynne)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.119.2...4.120.0>

###
[`v4.119.2`](https://redirect.github.com/vapor/vapor/releases/tag/4.119.2):
- Fix parallel build failures on platforms with Glibc

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.119.1...4.119.2)

#### What's Changed

Fix parallel build failures on platforms with Glibc by
[@&#8203;simonjbeaumont](https://redirect.github.com/simonjbeaumont) in
[#&#8203;3393](https://redirect.github.com/vapor/vapor/issues/3393)

> ## Motivation
>
> Since adding `MemberImportVisibility`, when Vapor is compiled in
highly parallel environments it fails with high probability:
>
> ```console
> % git rev-parse HEAD
> ac3aeb7730b63f4f54248603c38137b551b465c7
>
> % rm -rf .build ~/.cache/org.swift.swiftpm/manifests/ && swift build
-j 64
> ...
> Building for debugging...
> /pwd/Sources/Vapor/Utilities/String+IsIPAddress.swift:10:24: error:
initializer 'init()' is not available due to missing import of defining
module 'CNIOLinux' [#Membe
> rImportVisibility]
>  1 | import Foundation
>  2 | import NIOCore
>  3 | #if canImport(Android)
>    | `- note: add import of module 'CNIOLinux'
>  4 | import Android
>  5 | #endif
>    :
>  8 |     func isIPAddress() -> Bool {
> 9 | // We need some scratch space to let inet_pton write into.
> 10 |         var ipv4Addr = in_addr()
> | `- error: initializer 'init()' is not available due to missing
import of defining module 'CNIOLinux' [#MemberImportVisibility]
> 11 |         var ipv6Addr = in6_addr()
> 12 |
>
> ---[ similar error for in6_addr t…
> ```

###### *This patch was released by
[@&#8203;0xTim](https://redirect.github.com/0xTim)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.119.1...4.119.2>

###
[`v4.119.1`](https://redirect.github.com/vapor/vapor/releases/tag/4.119.1):
- Fix a couple of import issues

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.119.0...4.119.1)

#### What's Changed

Fix a couple of import issues by
[@&#8203;0xTim](https://redirect.github.com/0xTim) in
[#&#8203;3390](https://redirect.github.com/vapor/vapor/issues/3390)

> Fixes a couple of import issues seen recently:
>
> - Sendable error with TOTP types on old macOS SDKs - CryptoKit types
have Sendable annotations from Xcode 16.3 (Swift 6.1). If trying to
compile on older versions of Xcode, which we support you get an error in
Swift 6 mode
> - Some UBI9 based images complain about a missing import for CNIOLinux

###### *This patch was released by
[@&#8203;gwynne](https://redirect.github.com/gwynne)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.119.0...4.119.1>

###
[`v4.119.0`](https://redirect.github.com/vapor/vapor/releases/tag/4.119.0):
- Expose peer certificates in request handlers

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.118.0...4.119.0)

#### What's Changed

Expose peer certificates in request handlers by
[@&#8203;josephnoir](https://redirect.github.com/josephnoir) in
[#&#8203;3362](https://redirect.github.com/vapor/vapor/issues/3362)

> Additional certificate information can be relevant in mTLS
deployments. This PR exposes the certificate chain of the peer per
request. In contrast to
[#&#8203;3352](https://redirect.github.com/vapor/vapor/issues/3352),
this includes not just the leaf but the validated peer certificate
chain, i.e., the certificates that establish trust of the peer identity
from the leaf to (and including) the root certificate.
>
> The validated certificate chain is only available when setting a
custom verification callback with metadata. Configuration of this
callback is made available in this PR. It also adds a dependency on
`swift-certificates` to use `X509.ValidatedCertificateChain` for the
certificate chain.
>
> Example usage:
>
> ```swift
> app.get { req async in
>   if let chain = req.peerCertificateChain {
> return "I am trusting you because I trust: \(chain.root.description)"
>   } else {
>     return "I am not trusting you."
>   }
> }
> ```
>
> I suggest close
[#&#8203;3352](https://redirect.github.com/vapor/vapor/issues/3352) in
favor of this PR.

###### *This patch was released by
[@&#8203;0xTim](https://redirect.github.com/0xTim)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.118.0...4.119.0>

###
[`v4.118.0`](https://redirect.github.com/vapor/vapor/releases/tag/4.118.0):
- Update minimum Swift version to 6.0

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.117.2...4.118.0)

#### What's Changed

Update minimum Swift version to 6.0 by
[@&#8203;gwynne](https://redirect.github.com/gwynne) in
[#&#8203;3365](https://redirect.github.com/vapor/vapor/issues/3365)

> Clean up all the relevant `#if` conditionals, add theme settings to
the API documentation, and clean up the tests. (FileTests and
AsyncFileTests no longer crash on ten different force-unwraps when
`#file` (now `#filePath`) is inaccessible.)
>
> The tests now also build and pass on iOS, watchOS, tvOS, and visionOS.

#### Reviewers

Thanks to the reviewers for their help:

- [@&#8203;MahdiBM](https://redirect.github.com/MahdiBM)

###### *This patch was released by
[@&#8203;0xTim](https://redirect.github.com/0xTim)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.117.2...4.118.0>

###
[`v4.117.2`](https://redirect.github.com/vapor/vapor/releases/tag/4.117.2):
- Fixing error in documentation of HTTPHeaders accept variable

[Compare
Source](https://redirect.github.com/vapor/vapor/compare/4.117.1...4.117.2)

#### What's Changed

Fixing error in documentation of HTTPHeaders accept variable by
[@&#8203;VerticalHeretic](https://redirect.github.com/VerticalHeretic)
in [#&#8203;3375](https://redirect.github.com/vapor/vapor/issues/3375)

> This fix is addressing an issue
[vapor/docs#1098](https://redirect.github.com/vapor/docs/issues/1098),
and it’s fixing one of two of the problem mentioned there. The one being
that the accept variables is accessible on the headers variable of the
httpRequest. I couldn’t reproduce the second problem while it is working
correctly on Swift 6.2, and indeed I can make use `.html` as a condition
for the media types.
>
> As on the screenshot below: <img width="668" height="98" alt="image"
src="https://github.com/user-attachments/assets/9d54b6dc-26eb-48b0-bb53-0a8f0d829afd"
/>

###### *This patch was released by
[@&#8203;0xTim](https://redirect.github.com/0xTim)*

**Full Changelog**:
<https://github.com/vapor/vapor/compare/4.117.1...4.117.2>

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0My4zMS4xIiwidXBkYXRlZEluVmVyIjoiNDMuMzEuMSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

---------

Co-authored-by: cgrindel-self-hosted-renovate[bot] <139595543+cgrindel-self-hosted-renovate[bot]@users.noreply.github.com>
Co-authored-by: Chuck Grindel <chuck.grindel@gmail.com>
Co-authored-by: Claude Opus 4.6 <noreply@anthropic.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>