fix: support implicit resource localization (#1702)
Adding a dependency on https://github.com/mapbox/mapbox-navigation-ios
caused the following error:

```
ERROR: .../rules_swift_package_manager++swift_deps+swiftpkg_mapbox_navigation_ios/BUILD.bazel:55:34: Label '@@rules_swift_package_manager++swift_deps+swiftpkg_mapbox_navigation_ios//:Sources/MapboxNavigation/Resources/Base.lproj/Navigation.storyboard' is duplicated in the 'resources' attribute of rule 'MapboxNavigation.rspm_resource_bundle'
```

This is because [this
file](https://github.com/mapbox/mapbox-navigation-ios/tree/v2.18.4/Sources/MapboxNavigation/Resources/Base.lproj)
was being added both from `desc_map` and as a discovered resource. They
aren't being deduplicated in `resources_set` because the `desc_map`
instance has localization `"Base"`, but the discovered resource had
`None` for its localization.

This PR is intended to match the behavior of [this
code](https://github.com/swiftlang/swift-package-manager/blob/2f03e7a16e2c4d08a3a16f16cca627ff53b70271/Sources/PackageLoading/TargetSourcesBuilder.swift#L312-L318)
in SPM.

Alternatively we could deduplicate the labels themselves closer to where
the build file is constructed if there's no need to track the
localizations.

---------

Co-authored-by: Chuck Grindel <chuck@revealtech.ai>